name: Build and Deploy VitePress via FTP

on:
  push:
    branches: [main]  # 你的分支名
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 如果是 pnpm 项目，保留以下设置
      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build with VitePress
        run: pnpm run build  # 确保生成到 .vitepress/dist 目录

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 下载构建好的 dist 目录（来自 build 任务）
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .vitepress/dist
          path: .vitepress/dist

      # FTP 部署步骤（替换原来的 GitHub Pages 部署）
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .vitepress/dist/  # VitePress 默认输出目录
          server-dir: ./  # 远程服务器目标路径
          exclude: |
            .DS_Store
            *.md
          force: true
        env:
          LOG_LEVEL: verbose  # 调试时启用详细日志